[ai_lab]
# Target host for AI Lab setup
# Update IP address as needed
ai-lab ansible_host=192.168.1.38 ansible_user=jordi ansible_python_interpreter=/usr/bin/python3

[ai_lab:vars]
# Ansible settings
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
